blueprint:
  name: X-Sense Smoke Alarm Alexa Announcer (Multi-Detector)
  description: Monitor multiple X-Sense smoke alarms (20+) and announce alerts on Alexa devices. Create one automation per detector or use a group.
  domain: automation
  input:
    # Smoke Detector Group or Single Entity
    smoke_detector_trigger:
      name: Smoke Detector Trigger
      description: Single smoke detector entity, group, or area to monitor
      selector:
        entity:
          domain: 
            - binary_sensor
            - group
    
    # Alexa Devices
    alexa_devices:
      name: Alexa Devices
      description: Alexa devices to announce on (can select multiple)
      selector:
        target:
          entity:
            domain: media_player
            integration: alexa_media
    
    # Announcement Settings
    announcement_volume:
      name: Announcement Volume
      description: Volume level for announcements (0.0 to 1.0)
      default: 0.8
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1
          mode: slider
    
    repeat_announcements:
      name: Repeat Announcements
      description: Number of times to repeat the announcement
      default: 3
      selector:
        number:
          min: 1
          max: 10
          mode: slider
    
    repeat_delay:
      name: Delay Between Repeats
      description: Seconds to wait between repeated announcements
      default: 5
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: seconds
    
    # Fallback room name
    fallback_room_name:
      name: Fallback Room Name
      description: Room name to use if area/room cannot be determined
      default: "unknown location"
      selector:
        text:

mode: parallel
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input smoke_detector_trigger
    to: "on"

action:
  - alias: "Set volume on Alexa devices"
    action: media_player.volume_set
    target: !input alexa_devices
    data:
      volume_level: !input announcement_volume
  
  - alias: "Get triggered detector info and announce"
    variables:
      triggered_entity: "{{ trigger.entity_id }}"
      friendly_name: "{{ state_attr(trigger.entity_id, 'friendly_name') or trigger.entity_id }}"
      area_name: >
        {% set device = device_id(trigger.entity_id) %}
        {% if device %}
          {% set area = area_id(device) %}
          {% if area %}
            {{ area_name(area) }}
          {% else %}
            unknown location
          {% endif %}
        {% else %}
          unknown location
        {% endif %}
  
  - repeat:
      count: !input repeat_announcements
      sequence:
        - alias: "Update last called device"
          action: alexa_media.update_last_called
        - alias: "Announce smoke detected with room info"
          action: media_player.play_media
          target: !input alexa_devices
          data:
            media_content_type: "custom"
            media_content_id: "Simon says Smoke alarm activated. Evacuate now."
        - delay: !input repeat_delay